=== dzyanis/roadmap/tools/materials.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="tags">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="include">
        <xs:attribute name="filepath" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="translate">
        <xs:attribute name="lang" type="xs:string" use="required"/>
        <xs:attribute name="url" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="material">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="url" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="translate" type="translate" minOccurs="0"/>
            <xs:element name="tags" type="tags"/>
        </xs:sequence>
        <xs:attribute name="lang" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="materials">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="include" type="include" maxOccurs="unbounded"/>
                    <xs:element name="article" type="material" maxOccurs="unbounded"/>
                    <xs:element name="course" type="material" maxOccurs="unbounded"/>
                    <xs:element name="book" type="material" maxOccurs="unbounded"/>
                    <xs:element name="video" type="material" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dzyanis/roadmap/subjects/os/materials.xml
<?xml version="1.0" encoding="UTF-8"?>
<materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tools/materials.xsd">
    <book lang="en">
        <title>Docker in Action</title>
        <url>https://pepa.holla.cz/wp-content/uploads/2016/10/Docker-in-Action.pdf</url>
        <tags>
            <tag>os_virtualization_level_docker</tag>
        </tags>
    </book>
    
    <book lang="en">
        <title>Modern Operating Systems (4th Edition)</title>
        <url>https://www.amazon.com/Modern-Operating-Systems-Andrew-Tanenbaum/dp/013359162X</url>
        <tags>
            <tag>os</tag>
        </tags>
    </book>
    
    <book lang="en">
        <title>Operating System Concepts, Tenth Edition</title>
        <url>http://os-book.com/OS10/index.html</url>
        <tags>
            <tag>os</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Operating Systems, 3rd Edition</title>
        <url>https://www.amazon.com/Operating-Systems-3rd-Harvey-Deitel/dp/0131828274</url>
        <tags>
            <tag>os</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Operating Systems, 3rd Edition</title>
        <url>https://www.amazon.com/Operating-Systems-3rd-Harvey-Deitel/dp/0131828274</url>
        <tags>
            <tag>os</tag>
        </tags>
    </book>
    
    <video lang="en">
        <title>Files and File Systems: Crash Course Computer Science #20</title>
        <url>https://www.youtube.com/watch?v=KN8YgJnShPM</url>
        <tags>
            <tag>os_filesystem</tag>
        </tags>
    </video>
</materials>

=== dzyanis/roadmap/subjects/db/materials.xml
<?xml version="1.0" encoding="UTF-8"?>
<materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tools/materials.xsd">
    <article lang="en">
        <title>NOSQL</title>
        <url>https://martinfowler.com/nosql.html</url>
        <tags>
            <tag>db_nosql</tag>
        </tags>
    </article>

    <book lang="en">
        <title>NoSQL Distilled</title>
        <url>https://martinfowler.com/books/nosql.html</url>
        <tags>
            <tag>db_nosql</tag>
        </tags>
    </book>

    <book lang="en">
        <title>SQL Bible</title>
        <url>https://www.amazon.com/SQL-Bible-Alex-Kriegel/dp/0470229063</url>
        <tags>
            <tag>db_sql</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Oracle PL/SQL Programming: Covers Versions Through Oracle Database 12c</title>
        <url>https://www.amazon.com/Oracle-PL-SQL-Programming-Versions/dp/1449324452</url>
        <tags>
            <tag>db_relational_oracle</tag>
        </tags>
    </book>
    
    <book lang="en">
        <title>Kubernetes in Action</title>
        <url>https://www.manning.com/books/kubernetes-in-action</url>
        <tags>
            <tag>dev_orchestration_k8s</tag>
        </tags>
    </book>
</materials>

=== dzyanis/roadmap/stacks/java/materials.xml
<?xml version="1.0" encoding="UTF-8"?>
<materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tools/materials.xsd">
    <include filepath="subjects/cs/materials.xml"/>
    <include filepath="subjects/db/materials.xml"/>
    <include filepath="subjects/dev/materials.xml"/>
    <include filepath="subjects/net/materials.xml"/>
    <include filepath="subjects/java/materials.xml"/>
    
    <article lang="ru">
        <title>Логирование в Java / quick start</title>
        <url>https://habr.com/ru/post/130195/</url>
        <tags>
            <tag>dev_debugging_logging</tag>
        </tags>
    </article>

    <article lang="ru">
        <title>Инструменты логирование в Java</title>
        <url>https://habr.com/ru/sandbox/20634/</url>
        <tags>
            <tag>dev_debugging_logging</tag>
        </tags>
    </article>
    
    <book lang="en">
        <title>Practical Unit Testing with JUnit and Mockito</title>
        <url>https://www.amazon.com/Practical-Unit-Testing-JUnit-Mockito/dp/8393489393</url>
        <tags>
            <tag>dev_testing</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Data Structures and Algorithms in Java, 2nd Edition</title>
        <url>https://www.amazon.com/Data-Structures-Algorithms-Java-2nd/dp/0672324539</url>
        <tags>
            <tag>cs_algorithms</tag>
        </tags>
    </book>
    
    <book lang="en">
        <title>Grokking Algorithms: An illustrated guide for programmers and other curious people</title>
        <url>https://www.amazon.com/Grokking-Algorithms-illustrated-programmers-curious/dp/1617292230</url>
        <tags>
            <tag>cs_algorithms</tag>
        </tags>
    </book>
    
    <book lang="en">
        <title>Professional Java EE Design Patterns</title>
        <url>https://www.amazon.com/Professional-Java-EE-Design-Patterns/dp/111884341X</url>
        <tags>
            <tag>cs_architecture_patterns</tag>
        </tags>
    </book>
</materials>

=== dzyanis/roadmap/subjects/java/materials.xml
<?xml version="1.0" encoding="UTF-8"?>
<materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tools/materials.xsd">
    <book lang="en">
        <title>Oracle Certified Associate Java SE 8 Programmer I Study Guide (2015)</title>
        <url>https://www.amazon.com/OCA-Certified-Associate-Programmer-1Z0-808/dp/1118957407</url>
        <tags>
            <tag>java_se_core</tag>
        </tags>
    </book>

    <book lang="en">
        <title>OCP: Oracle Certified Professional Java SE 8 Programmer II Study Guide (2015)</title>
        <url>https://www.amazon.com/OCP-Certified-Professional-Programmer-2015-12-21/dp/B01A1MN0ZS</url>
        <tags>
            <tag>java_se_core</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Java 8 Lambdas: Functional Programming For The Masses</title>
        <url>https://www.amazon.com/Java-Lambdas-Functional-Programming-Masses/dp/1449370772</url>
        <tags>
            <tag>java_se_core</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Java: A Beginner's Guide, Eighth Edition</title>
        <url>https://www.amazon.com/Java-Beginners-Eighth-Herbert-Schildt/dp/1260440214</url>
        <tags>
            <tag>java_se_core</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Java Concurrency in Practice</title>
        <url>https://www.amazon.com/Java-Concurrency-Practice-Brian-Goetz/dp/0321349601</url>
        <tags>
            <tag>java_se_core</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Beginning Java E.E. 7 (Expert Voice in Java)</title>
        <url>https://www.amazon.com/gp/product/143024626X</url>
        <tags>
            <tag>java_ee</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Java EE 7 Essentials: Enterprise Developer Handbook</title>
        <url>https://www.amazon.com/Java-EE-Essentials-Enterprise-Developer/dp/1449370179</url>
        <tags>
            <tag>java_ee</tag>
        </tags>
    </book>

    <video lang="en">
        <title>JUGLviv meetup: Spring Boot the Ripper</title>
        <url>https://www.youtube.com/watch?v=8xa0RWMwAOE</url>
        <tags>
            <tag>java_spring</tag>
        </tags>
    </video>

    <video lang="en">
        <title>Евгений Борисов — Spring-потрошитель, часть 1</title>
        <url>https://www.youtube.com/watch?v=BmBr5diz8WA</url>
        <tags>
            <tag>java_spring</tag>
        </tags>
    </video>

    <book lang="en">
        <title>Cloud Native Java: Designing Resilient Systems with Spring Boot,
            Spring Cloud, and Cloud Foundry
        </title>
        <url>
            https://www.amazon.com/Cloud-Native-Java-Designing-Resilient/dp/1449374646
        </url>
        <tags>
            <tag>java_spring</tag>
        </tags>
    </book>

    <book lang="ru">
        <title>Spring 4 для профессионалов | Шефер Крис, Хо Кларенс</title>
        <url>https://www.ozon.ru/context/detail/id/33056979/</url>
        <tags>
            <tag>java_spring</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Spring in Action 5th Edition</title>
        <url>https://www.amazon.com/Spring-Action-Craig-Walls/dp/1617294942
        </url>
        <tags>
            <tag>java_spring</tag>
        </tags>
    </book>
    
    <book lang="en">
        <title>Pro Spring</title>
        <url>https://www.amazon.com/Pro-Spring-Clarence-Ho-ebook/dp/B014P9HJ0A
        </url>
        <tags>
            <tag>java_spring</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Java Persistence API i Hibernate</title>
        <url>https://www.amazon.com/Java-Persistence-API-i-Hibernate/dp/597060674X</url>
        <tags>
            <tag>java_orm_hibernate</tag>
        </tags>
    </book>

    <article lang="en">
        <title>Hibernate Getting Started Guide</title>
        <url>https://docs.jboss.org/hibernate/orm/4.2/devguide/en-US/html_single/#d5e58</url>
        <tags>
            <tag>java_orm_hibernate</tag>
        </tags>
    </article>

    <book lang="en">
        <title>Hibernate in Action</title>
        <url>
            https://www.amazon.com/Hibernate-Action-Christian-Bauer/dp/193239415X
        </url>
        <tags>
            <tag>java_orm_hibernate</tag>
        </tags>
    </book>
</materials>

=== dzyanis/roadmap/subjects/dev/materials.xml
<?xml version="1.0" encoding="UTF-8"?>
<materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tools/materials.xsd">
    <article lang="en">
        <title>Manifesto for Agile Software Development</title>
        <url>https://agilemanifesto.org</url>
        <tags>
            <tag>management_paradigms_agile</tag>
        </tags>
    </article>

    <article lang="en">
        <title>The Twelve-Factor App</title>
        <url>https://12factor.net</url>
        <tags>
            <tag>dev_methodologies_12factors</tag>
        </tags>
    </article>

    <book lang="en">
        <title>Test Driven Development: By Example</title>
        <url>https://www.amazon.com/Test-Driven-Development-Kent-Beck/dp/0321146530</url>
        <tags>
            <tag>dev_testing</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Working Effectively with Legacy Code</title>
        <url>https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052</url>
        <tags>
            <tag>dev</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Refactoring: Improving the Design of Existing Code</title>
        <url>https://www.amazon.com/Refactoring-Improving-Design-Existing-Code/dp/0201485672</url>
        <tags>
            <tag>dev</tag>
        </tags>
    </book>

    <book lang="en">
        <title>The Pragmatic Programmer: From Journeyman to Master</title>
        <url>https://www.amazon.com/Pragmatic-Programmer-Journeyman-Master/dp/020161622X</url>
        <tags>
            <tag>dev</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Code Complete: A Practical Handbook of Software Construction</title>
        <url>https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670</url>
        <tags>
            <tag>dev</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Clean Code: A Handbook of Agile Software Craftsmanship</title>
        <url>https://www.amazon.com/gp/product/0132350882</url>
        <tags>
            <tag>dev</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Goal: A Process of Ongoing Improvement</title>
        <url>https://www.amazon.com/Goal-Process-Ongoing-Improvement/dp/0884271951</url>
        <tags>
            <tag>dev_management</tag>
        </tags>
    </book>

    <book lang="en">
        <title>Pro Git</title>
        <url>https://git-scm.com/book/en</url>
        <tags>
            <tag>dev_version_git</tag>
        </tags>
    </book>
    
    <article lang="ru">
        <title>Системы сборки проектов Maven</title>
        <url>http://www.apache-maven.ru/</url>
        <tags>
            <tag>dev_build_maven</tag>
        </tags>
    </article>

    <article lang="ru">
        <title>Идеальный мавен. Часть 2: структура проекта</title>
        <url>https://habr.com/ru/post/344480/</url>
        <tags>
            <tag>dev_build_maven</tag>
        </tags>
    </article>

    <book lang="en">
        <title>Gradle in Action</title>
        <url>http://barbra-coco.dyndns.org/student/Gradle%20in%20Action.pdf</url>
        <tags>
            <tag>dev_build_gradle</tag>
        </tags>
    </book>

    <article lang="ru">
        <title>Ещё раз про семь основных методологий разработки</title>
        <url>https://habr.com/ru/company/edison/blog/269789/</url>
        <tags>
            <tag>dev_methodologies</tag>
        </tags>
    </article>

    <article lang="ru">
        <title>4 книги о системах контроля версий, которые дадут о них полное представление</title>
        <url>https://tproger.ru/books/4-books-about-vcs/</url>
        <tags>
            <tag>dev_version</tag>
        </tags>
    </article>

    <article lang="ru">
        <title>Введение в ELK: собираем, фильтруем и анализируем большие данные</title>
        <url>https://mkdev.me/posts/vvedenie-v-elk-sobiraem-filtruem-i-analiziruem-bolshie-dannye</url>
        <tags>
            <tag>dev_debugging_logging</tag>
        </tags>
    </article>
    
    <article lang="en">
        <title>The Practical Test Pyramid</title>
        <url>https://martinfowler.com/articles/practical-test-pyramid.html</url>
        <tags>
            <tag>dev_testing</tag>
        </tags>
    </article>
    
    <article lang="en">
        <title>How deep are your unit tests?</title>
        <url>
            https://stackoverflow.com/questions/153234/how-deep-are-your-unit-tests
        </url>
        <tags>
            <tag>dev_testing</tag>
        </tags>
    </article>

    <book lang="ru">
        <title>Джедайские техники</title>
        <url>https://www.mann-ivanov-ferber.ru/books/dzhedajskie-texniki/</url>
        <tags>
            <tag>management_time</tag>
        </tags>
    </book>
    
    <book lang="en">
        <title>Continuous delivery. Практика непрерывных апдейтов</title>
        <url>https://www.piter.com/product_by_id/87629352</url>
        <tags>
            <tag>dev_deployment_cd</tag>
        </tags>
    </book>
</materials>
