=== dzyanis/roadmap/tools/xmlgraph.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation source="http://graphml.graphdrawing.org/" xml:lang="en">
            This document defines the XMLGraph language including
        </xs:documentation>
    </xs:annotation>

    <xs:complexType name="include">
        <xs:attribute name="filepath" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="node">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="edge">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="source" type="xs:string" use="required"/>
        <xs:attribute name="target" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="graph">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="node" type="node" maxOccurs="unbounded"/>
                <xs:element name="edge" type="edge" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="xmlgraph">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="include" type="include" maxOccurs="unbounded"/>
                    <xs:element name="graph" type="graph" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dzyanis/roadmap/subjects/java/roadmap.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlgraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../tools/xmlgraph.xsd"
>
    <graph id="java">
        <node id="java" label="Java"/>

        <!-- java -->
        <node id="java_core" label="Core"/>
        <edge id="edge_java_core" source="java" target="java_core"/>

        <node id="java_jdk" label="JDK"/>
        <edge id="edge_java_jdk" source="java" target="java_jdk"/>

        <node id="java_ee" label="Enterprise Edition"/>
        <edge id="edge_java_ee" source="java" target="java_ee"/>

        <node id="java_spring" label="Spring Framework"/>
        <edge id="edge_java_spring" source="java" target="java_spring"/>

        <node id="java_3d_part" label="Third Party Libraries"/>
        <edge id="edge_java_3d_part" source="java" target="java_3d_part"/>

        <node id="java_persistence" label="Data Persistence"/>
        <edge id="edge_java_persistence" source="java" target="java_persistence"/>

        <node id="java_testing" label="Testing Frameworks"/>
        <edge id="edge_java_testing" source="java" target="java_testing"/>

        <!-- Java Core-->
        <node id="java_core_multithreading" label="Multithreading"/>
        <edge id="edge_java_core_multithreading" source="java_core" target="java_core_multithreading"/>

        <node id="java_core_io" label="I/O"/>
        <edge id="edge_java_core_io" source="java_core" target="java_core_io"/>

        <node id="java_core_collections" label="Collections"/>
        <edge id="edge_java_core_collections" source="java_core" target="java_core_collections"/>

        <node id="java_core_stream_api" label="Stream API"/>
        <edge id="edge_java_core_stream_api" source="java_core" target="java_core_stream_api"/>

        <node id="java_core_reflection_api" label="Reflection API"/>
        <edge id="edge_java_core_reflection_api" source="java_core" target="java_core_reflection_api"/>

        <!-- JDK -->
        <node id="java_jdk_jvm" label="JVM"/>
        <edge id="edge_java_jdk_jvm" source="java_jdk" target="java_jdk_jvm"/>

        <node id="java_jdk_tools" label="Tools"/>
        <edge id="edge_java_jdk_tools" source="java_jdk" target="java_jdk_tools"/>

        <!-- Java EE Development -->
        <node id="java_ee_ejb" label="EJB"/>
        <edge id="edge_java_ee_ejb" source="java_ee" target="java_ee_ejb"/>

        <node id="java_ee_components" label="Web Components"/>
        <edge id="edge_java_ee_components" source="java_ee" target="java_ee_components"/>

        <node id="java_ee_services" label="Web Services"/>
        <edge id="edge_java_ee_services" source="java_ee" target="java_ee_services"/>

        <!-- Spring Framework -->
        <node id="java_spring_core" label="Core"/>
        <edge id="edge_java_spring_core" source="java_spring" target="java_spring_core"/>

        <node id="java_spring_mvc" label="MVC"/>
        <edge id="edge_java_spring_mvc" source="java_spring" target="java_spring_mvc"/>

        <node id="java_spring_data" label="Data"/>
        <edge id="edge_java_spring_data" source="java_spring" target="java_spring_data"/>

        <node id="java_spring_security" label="Security"/>
        <edge id="edge_java_spring_security" source="java_spring" target="java_spring_security"/>

        <node id="java_spring_boot" label="Boot"/>
        <edge id="edge_java_spring_boot" source="java_spring" target="java_spring_boot"/>

        <node id="java_spring_cloud" label="Cloud"/>
        <edge id="edge_java_spring_cloud" source="java_spring" target="java_spring_cloud"/>

        <!-- Third Party Libraries -->
        <node id="java_3d_part_apache" label="Apache Commons"/>
        <edge id="edge_java_3d_part_apache" source="java_3d_part" target="java_3d_part_apache"/>

        <node id="java_3d_part_logging" label="Logging Libraries"/>
        <edge id="edge_java_3d_part_logging" source="java_3d_part" target="java_3d_part_logging"/>

        <node id="java_3d_part_json" label="Json Libraries"/>
        <edge id="edge_java_3d_part_json" source="java_3d_part" target="java_3d_part_json"/>

        <!-- Data Persistence -->
        <node id="java_persistence_jdbc" label="JDBC"/>
        <edge id="edge_java_persistence_jdbc" source="java_persistence" target="java_persistence_jdbc"/>

        <node id="java_persistence_jpa" label="JPA"/>
        <edge id="edge_java_persistence_jpa" source="java_persistence" target="java_persistence_jpa"/>

        <!-- JPA -->
        <node id="java_persistence_jpa_hibernate" label="Hibernate"/>
        <edge id="edge_java_persistence_jpa_hibernate" source="java_persistence_jpa" target="java_persistence_jpa_hibernate"/>

        <node id="java_persistence_jpa_eclipselink" label="EclipseLink"/>
        <edge id="edge_java_persistence_jpa_eclipselink" source="java_persistence_jpa" target="java_persistence_jpa_eclipselink"/>

        <node id="java_persistence_jpa_batis" label="iBATIS/MyBatis"/>
        <edge id="edge_java_persistence_jpa_batis" source="java_persistence_jpa" target="java_persistence_jpa_batis"/>

        <!-- Testing -->
        <node id="java_testing_testng" label="TestNG"/>
        <edge id="edge_java_testing_testng" source="java_testing" target="java_testing_testng"/>

        <node id="java_testing_junit" label="JUnit"/>
        <edge id="edge_java_testing_junit" source="java_testing" target="java_testing_junit"/>

        <node id="java_testing_mokito" label="Mokito"/>
        <edge id="edge_java_testing_mokito" source="java_testing" target="java_testing_mokito"/>
    </graph>
</xmlgraph>

=== dzyanis/roadmap/subjects/os/roadmap.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlgraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../tools/xmlgraph.xsd"
>
    <graph id="os">
        <node id="os" label="Operating System"/>

        <!--Operating System-->
        <node id="os_virtual_memory" label="Virtual Memory"/>
        <edge id="edge_os_virtual_memory" source="os" target="os_virtual_memory"/>

        <node id="os_threads" label="Threads"/>
        <edge id="edge_os_threads" source="os" target="os_threads"/>

        <node id="os_io" label="I/O"/>
        <edge id="edge_os_io" source="os" target="os_io"/>

        <node id="os_virtualization" label="Virtualization"/>
        <edge id="edge_os_virtualization" source="os" target="os_virtualization"/>

        <node id="os_shell" label="Command Language"/>
        <edge id="edge_os_shell" source="os" target="os_shell"/>

        <!--Virtualization-->
        <node id="os_virtualization_level" label="OS-level Virtualisation"/>
        <edge id="edge_os_virtualization_level" source="os_virtualization" target="os_virtualization_level"/>

        <node id="os_virtualization_x86" label="x86 Virtualization"/>
        <edge id="edge_os_virtualization_x86" source="os_virtualization" target="os_virtualization_x86"/>

        <!--OS-level Virtualisation-->
        <node id="os_virtualization_level_docker" label="Docker"/>
        <edge id="edge_os_virtualization_level_docker" source="os_virtualization_level" target="os_virtualization_level_docker"/>

        <node id="os_virtualization_level_nanobox" label="Nanobox"/>
        <edge id="edge_os_virtualization_level_nanobox" source="os_virtualization_level" target="os_virtualization_level_nanobox"/>

        <node id="os_virtualization_level_deis" label="Deis"/>
        <edge id="edge_os_virtualization_level_deis" source="os_virtualization_level" target="os_virtualization_level_deis"/>

        <node id="os_virtualization_level_mesos" label="Apache Mesos"/>
        <edge id="edge_os_virtualization_level_mesos" source="os_virtualization_level" target="os_virtualization_level_mesos"/>

        <!--x86 Virtualization-->
        <node id="os_virtualization_x86_virtualbox" label="VirtualBox"/>
        <edge id="edge_os_virtualization_x86_virtualbox" source="os_virtualization_x86" target="os_virtualization_x86_virtualbox"/>

        <node id="os_virtualization_x86_vmware" label="VMware"/>
        <edge id="edge_os_virtualization_x86_vmware" source="os_virtualization_x86" target="os_virtualization_x86_vmware"/>
    </graph>
</xmlgraph>

=== dzyanis/roadmap/subjects/cs/roadmap.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlgraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../tools/xmlgraph.xsd"
>
    <graph id="cs">
        <node id="cs" label="Computer Science"/>

        <node id="cs_architecture" label="Architecture knowledge"/>
        <edge id="edge_cs_architecture" source="cs" target="cs_architecture"/>

        <node id="code" label="Code Standards and Code Review Process"/>
        <edge id="edge_cs_code" source="cs" target="code"/>

        <node id="cs_algorithms" label="Algorithms and data structures"/>
        <edge id="edge_cs_algorithms" source="cs" target="cs_algorithms"/>

        <node id="systems" label="Systems Programming"/>
        <edge id="edge_cs_systems" source="cs" target="systems"/>

        <node id="testing" label="Testing processes"/>
        <edge id="edge_cs_testing" source="cs" target="testing"/>

        <!-- Algorithms and data structures -->
        <node id="cs_algorithms_analysis" label="Analysis"/>
        <edge id="edge_cs_algorithms_analysis" source="cs_algorithms" target="cs_algorithms_analysis"/>

        <node id="cs_algorithms_structures" label="Data Structures"/>
        <edge id="edge_cs_algorithms_structures" source="cs_algorithms" target="cs_algorithms_structures"/>

        <node id="cs_algorithms_algorithms" label="Algorithms"/>
        <edge id="edge_cs_algorithms_algorithms" source="cs_algorithms" target="cs_algorithms_algorithms"/>

        <!--Data Structures-->
        <node id="cs_algorithms_structures_lists" label="Lists"/>
        <edge id="edge_cs_algorithms_structures_lists" source="cs_algorithms_structures" target="cs_algorithms_structures_lists"/>

        <node id="cs_algorithms_structures_stacks" label="Stacks"/>
        <edge id="edge_cs_algorithms_structures_stacks" source="cs_algorithms_structures" target="cs_algorithms_structures_stacks"/>

        <node id="cs_algorithms_structures_queues" label="Queues"/>
        <edge id="edge_cs_algorithms_structures_queues" source="cs_algorithms_structures" target="cs_algorithms_structures_queues"/>

        <node id="cs_algorithms_structures_trees" label="Trees"/>
        <edge id="edge_cs_algorithms_structures_trees" source="cs_algorithms_structures" target="cs_algorithms_structures_trees"/>

        <node id="cs_algorithms_structures_heaps" label="Heaps"/>
        <edge id="edge_cs_algorithms_structures_heaps" source="cs_algorithms_structures" target="cs_algorithms_structures_heaps"/>

        <node id="cs_algorithms_structures_graphs" label="Graphs"/>
        <edge id="edge_cs_algorithms_structures_graphs" source="cs_algorithms_structures" target="cs_algorithms_structures_graphs"/>

        <!--Algorithms-->
        <node id="cs_algorithms_structures_sorting" label="Sorting algoritms"/>
        <edge id="edge_cs_algorithms_structures_sorting" source="cs_algorithms_algorithms" target="cs_algorithms_structures_sorting"/>

        <node id="cs_algorithms_structures_research" label="Reasearch algoritms"/>
        <edge id="edge_cs_algorithms_structures_research" source="cs_algorithms_algorithms" target="cs_algorithms_structures_research"/>

        <!--Architecture knowledge-->
        <node id="cs_architecture_microservices" label="Microservices"/>
        <edge id="edge_cs_architecture_microservices" source="cs_architecture" target="cs_architecture_microservices"/>

        <node id="cs_architecture_ddd" label="Domain-Driven Design"/>
        <edge id="edge_cs_architecture_ddd" source="cs_architecture" target="cs_architecture_ddd"/>

        <node id="cs_architecture_solid" label="SOLID"/>
        <edge id="edge_cs_architecture_solid" source="cs_architecture" target="cs_architecture_solid"/>

        <node id="cs_architecture_patterns" label="Design Patterns"/>
        <edge id="edge_cs_architecture_patterns" source="cs_architecture" target="cs_architecture_patterns"/>

        <node id="cs_architecture_event" label="Event Sourcing"/>
        <edge id="edge_cs_architecture_event" source="cs_architecture" target="cs_architecture_event"/>

        <node id="cs_architecture_oop" label="Object-Oriented Programming"/>
        <edge id="edge_cs_architecture_oop" source="cs_architecture" target="cs_architecture_oop"/>

        <node id="cs_architecture_func" label="Functional Programming"/>
        <edge id="edge_cs_architecture_func" source="cs_architecture" target="cs_architecture_func"/>

        <node id="cs_architecture_distributed" label="Distributed Systems"/>
        <edge id="edge_cs_cs_architecture_distributed" source="cs_architecture" target="cs_architecture_distributed"/>

        <!--Object-Oriented Programming-->
        <node id="cs_architecture_oop_encapsulation" label="Encapsulation"/>
        <edge id="edge_cs_architecture_oop_encapsulation" source="cs_architecture_oop" target="cs_architecture_oop_encapsulation"/>

        <node id="cs_architecture_oop_inheritance" label="Inheritance"/>
        <edge id="edge_cs_architecture_oop_inheritance" source="cs_architecture_oop" target="cs_architecture_oop_inheritance"/>

        <node id="cs_architecture_oop_polymorphism" label="Polymorphism"/>
        <edge id="edge_cs_architecture_oop_polymorphism" source="cs_architecture_oop" target="cs_architecture_oop_polymorphism"/>
    </graph>
</xmlgraph>

=== dzyanis/roadmap/subjects/dev/roadmap.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlgraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../tools/xmlgraph.xsd"
>
    <graph id="dev">
        <node id="dev" label="Software Development Processes"/>

        <!--Software Development Processes-->
        <node id="dev_paradigms" label="Paradigms and models"/>
        <edge id="edge_dev_paradigms" source="dev" target="dev_paradigms"/>

        <node id="dev_methodologies" label="Methodologies and frameworks"/>
        <edge id="edge_dev_methodologies" source="dev" target="dev_methodologies"/>

        <node id="dev_testing" label="Testing"/>
        <edge id="edge_dev_testing" source="dev" target="dev_testing"/>

        <node id="dev_trackers" label="Bug tracking systems"/>
        <edge id="edge_dev_trackers" source="dev" target="dev_trackers"/>

        <node id="dev_version" label="Version Control"/>
        <edge id="edge_dev_version" source="dev" target="dev_version"/>

        <node id="dev_deployment" label="Deployment"/>
        <edge id="edge_dev_deployment" source="dev" target="dev_deployment"/>

        <node id="dev_estimation" label="Estimations"/>
        <edge id="edge_dev_estimation" source="dev" target="dev_estimation"/>

        <node id="dev_debugging" label="Debugging"/>
        <edge id="edge_dev_debugging" source="dev" target="dev_debugging"/>

        <node id="dev_orchestration" label="Orchestration"/>
        <edge id="edge_dev_orchestration" source="dev" target="dev_orchestration"/>

        <node id="dev_management" label="Management"/>
        <edge id="edge_dev_management" source="dev" target="dev_management"/>

        <!--Orchestration-->
        <node id="dev_orchestration_ansible" label="Ansible"/>
        <edge id="edge_dev_orchestration_ansible" source="dev_orchestration" target="dev_orchestration_ansible"/>

        <node id="dev_orchestration_puppet" label="Puppet"/>
        <edge id="edge_dev_orchestration_puppet" source="dev_orchestration" target="dev_orchestration_puppet"/>

        <node id="dev_orchestration_k8s" label="Kubernetes"/>
        <edge id="edge_dev_orchestration_k8s" source="dev_orchestration" target="dev_orchestration_k8s"/>

        <!--Debugging-->
        <node id="dev_debugging_troubleshooting" label="Troubleshooting"/>
        <edge id="edge_dev_debugging_troubleshooting" source="dev_debugging" target="dev_debugging_troubleshooting"/>

        <node id="dev_debugging_logging" label="Logging"/>
        <edge id="edge_dev_debugging_logging" source="dev_debugging" target="dev_debugging_logging"/>

        <node id="dev_debugging_monitoring" label="Monitoring"/>
        <edge id="edge_dev_debugging_monitoring" source="dev_debugging" target="dev_debugging_monitoring"/>

        <!--Testing-->
        <node id="dev_testing_tdd" label="Test-driven development"/>
        <edge id="edge_dev_testing_tdd" source="dev_testing" target="dev_testing_tdd"/>

        <node id="dev_testing_bdd" label="Behavior-driven development"/>
        <edge id="edge_dev_testing_bdd" source="dev_testing" target="dev_testing_bdd"/>

        <!--Bug tracking systems-->
        <node id="dev_trackers_jira" label="Jira"/>
        <edge id="edge_dev_trackers_jira" source="dev_trackers" target="dev_trackers_jira"/>

        <node id="dev_trackers_redmine" label="Redmine"/>
        <edge id="edge_dev_trackers_redmine" source="dev_trackers" target="dev_trackers_redmine"/>

        <node id="dev_trackers_tfs" label="TFS"/>
        <edge id="edge_dev_trackers_tfs" source="dev_trackers" target="dev_trackers_tfs"/>

        <!--Version Control-->
        <node id="dev_version_git" label="Git"/>
        <edge id="edge_dev_version_git" source="dev_version" target="dev_version_git"/>

        <!--Deployment-->
        <node id="dev_deployment_ci" label="Continuous Integration"/>
        <edge id="edge_dev_deployment_ci" source="dev_deployment" target="dev_deployment_ci"/>

        <node id="dev_deployment_cd" label="Continuous Delivery"/>
        <edge id="edge_dev_deployment_cd" source="dev_deployment" target="dev_deployment_cd"/>

        <!--Paradigms and models-->
        <node id="management_paradigms_agile" label="Agile"/>
        <edge id="edge_management_paradigms_agile" source="dev_paradigms" target="management_paradigms_agile"/>

        <node id="management_paradigms_waterfall" label="Waterfall"/>
        <edge id="edge_management_paradigms_waterfall" source="dev_paradigms" target="management_paradigms_waterfall"/>

        <!--Methodologies and frameworks-->
        <node id="dev_methodologies_scrum" label="SCRUM"/>
        <edge id="edge_dev_methodologies_scrum" source="dev_methodologies" target="dev_methodologies_scrum"/>

        <node id="dev_methodologies_kanban" label="Kanban"/>
        <edge id="edge_dev_methodologies_kanban" source="dev_methodologies" target="dev_methodologies_kanban"/>

        <node id="dev_methodologies_xp" label="Extreme Programming"/>
        <edge id="edge_dev_methodologies_xp" source="dev_methodologies" target="dev_methodologies_xp"/>

        <node id="dev_methodologies_12factors" label="The Twelve-Factor App"/>
        <edge id="edge_dev_methodologies_12factors" source="dev_methodologies" target="dev_methodologies_12factors"/>

        <!--Estimations-->
        <node id="management_estimation_poker" label="Planning Poker"/>
        <edge id="edge_management_estimation_poker" source="dev_estimation" target="management_estimation_poker"/>
    </graph>
</xmlgraph>

=== dzyanis/roadmap/subjects/db/roadmap.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlgraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../tools/xmlgraph.xsd"
>
    <graph id="db">
        <node id="db" label="Databases"/>

        <node id="db_sql" label="SQL"/>
        <edge id="edge_db_sql" source="db" target="db_sql"/>

        <node id="db_indexes" label="Indexes"/>
        <edge id="edge_db_indexes" source="db" target="db_indexes"/>

        <node id="db_transactions" label="Transactions"/>
        <edge id="edge_db_transactions" source="db" target="db_transactions"/>

        <node id="db_principles" label="Principles"/>
        <edge id="edge_db_principles" source="db" target="db_principles"/>

        <node id="db_relational" label="Relational"/>
        <edge id="edge_db_relational" source="db" target="db_relational"/>

        <node id="db_nosql" label="NOSQL"/>
        <edge id="edge_db_nosql" source="db" target="db_nosql"/>

        <node id="db_search" label="Search Engines"/>
        <edge id="edge_db_search" source="db" target="db_search"/>

        <node id="db_message_broker" label="Message Broker"/>
        <edge id="edge_db_message_broker" source="db" target="db_message_broker"/>

        <!--Message Broker-->
        <node id="db_message_broker_kafka" label="Kafka"/>
        <edge id="edge_db_message_broker_kafka" source="db_message_broker" target="db_message_broker_kafka"/>

        <node id="db_message_broker_rabbit" label="RabbitMQ"/>
        <edge id="edge_db_message_broker_rabbit" source="db_message_broker" target="db_message_broker_rabbit"/>

        <node id="db_message_broker_awssqs" label="Amazon Simple Queue Service"/>
        <edge id="edge_db_message_broker_awssqs" source="db_message_broker" target="db_message_broker_awssqs"/>

        <!--Relational-->
        <node id="db_relational_mvcc" label="Multiversion Concurrency Control"/>
        <edge id="edge_db_relational_mvcc" source="db_relational" target="db_relational_mvcc"/>

        <node id="db_relational_blocking" label="Blocking"/>
        <edge id="edge_db_relational_blocking" source="db_relational" target="db_relational_blocking"/>

        <node id="db_relational_acid" label="ACID"/>
        <edge id="edge_db_relational_acid" source="db_relational" target="db_relational_acid"/>

        <node id="db_relational_oo" label="Object-oriented"/>
        <edge id="edge_db_relational_oo" source="db_relational" target="db_relational_oo"/>

        <!--Multiversion Concurrency Control-->
        <node id="db_relational_firebird" label="Firebird"/>
        <edge id="edge_db_relational_firebird" source="db_relational_mvcc" target="db_relational_firebird"/>
        <node id="db_relational_postgres" label="PostgreSQL"/>
        <edge id="edge_db_relational_postgres" source="db_relational_mvcc" target="db_relational_postgres"/>
        <node id="db_relational_oracle" label="Oracle"/>
        <edge id="edge_db_relational_oracle" source="db_relational_mvcc" target="db_relational_oracle"/>
        <node id="db_mysql" label="MySQL"/>
        <edge id="edge_db_relational_mvcc_mysql" source="db_relational_mvcc" target="db_mysql"/>

        <!--Blocking DB-->
        <edge id="edge_db_relational_blocking_mysql" source="db_relational_blocking" target="db_mysql"/>

        <!--NOSQL-->
        <node id="db_nosql_cap" label="CAP Theorem"/>
        <edge id="edge_db_nosql_cap" source="db_nosql" target="db_nosql_cap"/>

        <node id="db_nosql_base" label="BASE"/>
        <edge id="edge_db_nosql_base" source="db_nosql" target="db_nosql_base"/>

        <node id="db_nosql_graph" label="Graph database"/>
        <edge id="edge_db_nosql_graph" source="db_nosql" target="db_nosql_graph"/>

        <node id="db_nosql_doc" label="Document base"/>
        <edge id="edge_db_nosql_doc" source="db_nosql" target="db_nosql_doc"/>

        <node id="db_nosql_colbase" label="Column base"/>
        <edge id="edge_db_nosql_colbase" source="db_nosql" target="db_nosql_colbase"/>

        <node id="db_nosql_colwidebase" label="Wide column base"/>
        <edge id="edge_db_nosql_colwidebase" source="db_nosql" target="db_nosql_colwidebase"/>

        <node id="db_nosql_time" label="Time series"/>
        <edge id="edge_db_nosql_time" source="db_nosql" target="db_nosql_time"/>

        <!--Graph database-->
        <node id="db_nosql_orient" label="OrientDB"/>
        <edge id="edge_db_nosql_orient" source="db_nosql_graph" target="db_nosql_orient"/>

        <node id="db_nosql_neo4j" label="Neo4j"/>
        <edge id="edge_db_nosql_neo4j" source="db_nosql_graph" target="db_nosql_neo4j"/>

        <!--Document base-->
        <node id="db_nosql_mongo" label="MongoDB"/>
        <edge id="edge_db_nosql_mongo" source="db_nosql_doc" target="db_nosql_mongo"/>

        <!--Column base-->
        <node id="db_nosql_redis" label="Redis"/>
        <edge id="edge_db_nosql_redis" source="db_nosql_colbase" target="db_nosql_redis"/>

        <node id="db_nosql_clickhouse" label="ClickHouse"/>
        <edge id="edge_db_nosql_clickhouse" source="db_nosql_colbase" target="db_nosql_clickhouse"/>

        <!--Search Engines-->
        <node id="db_search_elasticseaerch" label="Elasticseaerch"/>
        <edge id="edge_db_search_elasticseaerch" source="db_search" target="db_search_elasticseaerch"/>

        <node id="db_search_sphinx" label="Sphinx"/>
        <edge id="edge_db_search_sphinx" source="db_search" target="db_search_sphinx"/>
    </graph>
</xmlgraph>

=== dzyanis/roadmap/subjects/net/roadmap.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlgraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../tools/xmlgraph.xsd"
>
    <graph id="net">
        <node id="net" label="Computer Network"/>

        <node id="net_osi" label="Open Systems Interconnection model"/>
        <edge id="edge_net_osi" source="net" target="net_osi"/>

        <node id="net_grpc" label="gRPC"/>
        <edge id="edge_net_grpc" source="net" target="net_grpc"/>

        <node id="net_restapi" label="REST API"/>
        <edge id="edge_net_restapi" source="net" target="net_restapi"/>

        <node id="net_graphql" label="GraphQL"/>
        <edge id="edge_net_graphql" source="net" target="net_graphql"/>

        <node id="net_soap" label="SOAP"/>
        <edge id="edge_net_soap" source="net" target="net_soap"/>

        <node id="net_dns" label="DNS"/>
        <edge id="edge_net_dns" source="net" target="net_dns"/>

        <node id="net_protocols" label="Protocols"/>
        <edge id="edge_net_protocols" source="net" target="net_protocols"/>

        <node id="net_websocket" label="Websocket"/>
        <edge id="edge_net_websocket" source="net" target="net_websocket"/>

        <node id="net_auth" label="Authorization and Authentication"/>
        <edge id="edge_net_auth" source="net" target="net_auth"/>

        <!--Protocols-->
        <node id="net_protocols_ip" label="IP"/>
        <edge id="edge_net_protocols_ip" source="net_protocols" target="net_protocols_ip"/>

        <node id="net_protocols_tcp" label="TCP"/>
        <edge id="edge_net_protocols_tcp" source="net_protocols" target="net_protocols_tcp"/>

        <node id="net_protocols_udp" label="UDP"/>
        <edge id="edge_net_protocols_udp" source="net_protocols" target="net_protocols_udp"/>

        <node id="net_protocols_http" label="HTTP"/>
        <edge id="edge_net_protocols_http" source="net_protocols" target="net_protocols_http"/>

        <node id="net_protocols_tls" label="TLS"/>
        <edge id="edge_net_protocols_tls" source="net_protocols" target="net_protocols_tls"/>

        <node id="net_protocols_ssl" label="SSL"/>
        <edge id="edge_net_protocols_ssl" source="net_protocols" target="net_protocols_ssl"/>

        <!--Authorization and Authentication-->
        <node id="net_auth_authorization" label="Authorization"/>
        <edge id="edge_net_auth_authorization" source="net_auth" target="net_auth_authorization"/>

        <node id="net_auth_authentication" label="Authentication"/>
        <edge id="edge_net_auth_authentication" source="net_auth" target="net_auth_authentication"/>

        <node id="net_auth_oauth" label="OAuth"/>
        <edge id="edge_net_auth_oauth" source="net_auth" target="net_auth_oauth"/>

        <node id="net_auth_jwt" label="JWT"/>
        <edge id="edge_net_auth_jwt" source="net_auth" target="net_auth_jwt"/>

        <node id="net_auth_cookie" label="Cookie"/>
        <edge id="edge_net_auth_cookie" source="net_auth" target="net_auth_cookie"/>
    </graph>
</xmlgraph>
